### ISSUE TITLE
pre-trained model for dataset

### ISSUE THREAD

**Issue by ghost** [vivoutlaw/UDMA#1]
In your dataset section in readme.md, you have mentioned "The feature was extracted using our pre-trained model on DeepFashion.", could you provide the pre-trained model and the related source codes?

**Comment by vivoutlaw** [comment]
## Taken from https://github.com/vivoutlaw/UDMA/blob/master/README.md
-  Download the pre-trained model trained on DeepFashion (`trainval set`) using Resnet101-TL-GeM model.
```bash
bash ./models/download_our_DF_model.sh DeepFashion
```
See the ## Finetuning Full section for feature extraction
