### ISSUE TITLE
Regarding the Access to the Dataset

### ISSUE THREAD

**Issue by indersingh17188** [vivoutlaw/UDMA#2]
Hello,

Thank you for the great work.

I would like to know if the datasets have been moved or do I need to request special access as I can not access the provided link for downloading the dataset using script download_dataset.sh

Thanks in advance.

**Comment by vivoutlaw** [comment]
Hi, here you go: https://cvhci.anthropomatik.kit.edu/~datasets-publisher/published_datasets/domain_adaption/UDMA/
