### ISSUE TITLE
cannot download pre-extracted features for datasets

### ISSUE THREAD

**Issue by Min-Hyuk98** [vivoutlaw/UDMA#3]
Hello
I'm trying to download the features you made but can't.
As you wrote in readme, when i execute bash ./features/download_dataset.sh DeepFashion, 404 error occurs
maybe the server doesn't exist
https://cvhci.anthropomatik.kit.edu/~vsharma/UDMA/features   this link doesn't exist
thank you for your work.

**Comment by YZX-codesky** [comment]
Hello, I have the same problem, have you solved it? I would be grateful if you could give me some help

**Comment by vivoutlaw** [comment]
Hi, the dataset and models are available here: https://cvhci.anthropomatik.kit.edu/~datasets-publisher/published_datasets/domain_adaption/UDMA/
